### ISSUE TITLE
io charts not rendering 

### ISSUE THREAD

**Issue by WesIngwersen** [modelearth/io#3]
IO charts should load here
https://model.earth/io/build/iochart.html#sectors=333613,335912,336111&page=1&count=10

they are linked to from the [model earth useeio widgets demo page](https://model.earth/io/build/), which in turn is linked to for seeing the example widgets from [USEPA useeio-widgets README](https://github.com/USEPA/useeio-widgets)

**Comment by WesIngwersen** [comment]
fyi @modelearth

**Comment by ModelEarth** [comment]
This works now. The .gitignore file was omitting the version 1.2 api folder.
